name: release
description: release a new version of the container image

inputs:
  cr-pat:
    description: Personal access token for the container registry
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ghcr.io/reproio/send-alb-metrics-to-datadog
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: reproiobot
        password: ${{ inputs.cr-pat }}
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
