name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr-tag: ${{ steps.run-tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - id: run-tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: tagpr
    if: needs.tagpr.outputs.tagpr-tag != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: reproiobot
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/reproio/send-alb-metrics-to-datadog:latest
            ghcr.io/reproio/send-alb-metrics-to-datadog:${{ steps.latest_version.outputs.version }}
          labels: |
            org.opencontainers.image.name=send-alb-metrics-to-datadog
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.latest_version.outputs.version }}
            org.opencontainers.image.source=https://github.com/reproio/send-alb-metrics-to-datadog
